### ISSUE TITLE
Python 2.7.5: Struct() argument 1 must be string, not unicode

### ISSUE THREAD

**Issue by joachimmetz** [libyal/dtfabric#11]
From: https://github.com/log2timeline/plaso/issues/1917

```
Traceback (most recent call last):
  File "/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/site-packages/plaso/cli/log2timeline_tool.py", line 368, in ExtractEventsFromSources
    scan_context = self.ScanSource(self._source_path)
  File "/usr/lib/python2.7/site-packages/plaso/cli/storage_media_tool.py", line 1099, in ScanSource
    self._source_scanner.Scan(scan_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 565, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 366, in _ScanNode
    scan_node.path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 55, in OpenFileEntry
    path_spec_object, resolver_context=resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 158, in OpenFileSystem
    resolver_helper = cls._GetResolverHelper(path_spec_object.type_indicator)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 35, in _GetResolverHelper
    from dfvfs.resolver_helpers import manager
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/__init__.py", line 10, in <module>
    from dfvfs.resolver_helpers import cpio_resolver_helper
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/cpio_resolver_helper.py", line 10, in <module>
    from dfvfs.vfs import cpio_file_system
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/cpio_file_system.py", line 6, in <module>
    from dfvfs.lib import cpio
  File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 43, in <module>
    class CPIOArchiveFile(data_format.DataFormat):
  File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 59, in CPIOArchiveFile
    'cpio_binary_big_endian_file_entry')
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1811, in CreateDataTypeMap
    return DataTypeMapFactory.CreateDataTypeMapByType(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1829, in CreateDataTypeMapByType
    return data_type_map_class(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1342, in __init__
    data_type_definition, self._data_type_map_cache)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1542, in _GetMemberDataTypeMaps
    member_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1829, in CreateDataTypeMapByType
    return data_type_map_class(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 217, in __init__
    self._operation = self._GetByteStreamOperation()
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 150, in _GetByteStreamOperation
    return byte_operations.StructOperation(format_string)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/byte_operations.py", line 55, in __init__
    'with error: {0!s}').format(exception))
dtfabric.errors.FormatError: Unable to create struct object from data type definition with error: Struct() argument 1 must be string, not unicode
```

**Comment by Lyro1** [comment]
I got almost exactly the same error : 
`Traceback (most recent call last):
  File "/bin/log2timeline.py", line 68, in <module>
    if not Main():
  File "/bin/log2timeline.py", line 54, in Main
    tool.ExtractEventsFromSources()
  File "/usr/lib/python2.7/site-packages/plaso/cli/log2timeline_tool.py", line 369, in ExtractEventsFromSources
    scan_context = self.ScanSource(self._source_path)
  File "/usr/lib/python2.7/site-packages/plaso/cli/storage_media_tool.py", line 1083, in ScanSource
    self._source_scanner.Scan(scan_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 565, in Scan
    self._ScanNode(scan_context, scan_node, auto_recurse=auto_recurse)
  File "/usr/lib/python2.7/site-packages/dfvfs/helpers/source_scanner.py", line 366, in _ScanNode
    scan_node.path_spec, resolver_context=self._resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 55, in OpenFileEntry
    path_spec_object, resolver_context=resolver_context)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 158, in OpenFileSystem
    resolver_helper = cls._GetResolverHelper(path_spec_object.type_indicator)
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver/resolver.py", line 35, in _GetResolverHelper
    from dfvfs.resolver_helpers import manager
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/__init__.py", line 10, in <module>
    from dfvfs.resolver_helpers import cpio_resolver_helper
  File "/usr/lib/python2.7/site-packages/dfvfs/resolver_helpers/cpio_resolver_helper.py", line 10, in <module>
    from dfvfs.vfs import cpio_file_system
  File "/usr/lib/python2.7/site-packages/dfvfs/vfs/cpio_file_system.py", line 6, in <module>
    from dfvfs.lib import cpio
  File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 43, in <module>
    class CPIOArchiveFile(data_format.DataFormat):
  File "/usr/lib/python2.7/site-packages/dfvfs/lib/cpio.py", line 59, in CPIOArchiveFile
    'cpio_binary_big_endian_file_entry')
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1881, in CreateDataTypeMap
    return DataTypeMapFactory.CreateDataTypeMapByType(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1899, in CreateDataTypeMapByType
    return data_type_map_class(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1412, in __init__
    data_type_definition, self._data_type_map_cache)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1612, in _GetMemberDataTypeMaps
    member_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 1899, in CreateDataTypeMapByType
    return data_type_map_class(data_type_definition)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 246, in __init__
    self._operation = self._GetByteStreamOperation()
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/data_maps.py", line 179, in _GetByteStreamOperation
    return byte_operations.StructOperation(format_string)
  File "/usr/lib/python2.7/site-packages/dtfabric/runtime/byte_operations.py", line 55, in __init__
    'with error: {0!s}').format(exception))
dtfabric.errors.FormatError: Unable to create struct object from data type definition with error: Struct() argument 1 must be string, not unicode
`

I was running the script on Python 2.7.10 on a CentOS minimal distribution, and found the topic above, in which you were considering that updating Python to 2.7.10 and above could fix the problem.
I tried with the 2.7.15 version, which did not fix the issue.
I also changed from 2.7.15 to 3.6.3, which did not fix the issue.

I run the command like so : `log2timeline.py path/to/save.test plaso/test_data/syslog_image.dd`

Do you have any idea why this happens ?

**Comment by ericzinnikas** [comment]
FWIW, removing `from __future__ import unicode_literals` from `runtime/byte_operations.py` and `runtime/data_maps.py` seems to let me use plaso successfully with Python 2.7.5

**Comment by joachimmetz** [comment]
@ericzinnikas thx for the suggestion, however with python 2 prior to 2.10 containing various ssl related bugs and the expected end of life of python 2 in 2020, I really would encourage using a more recent version of python.

**Comment by ericzinnikas** [comment]
Yup! Just using that to tide me over until we upgrade.

**Comment by joachimmetz** [comment]
With the Python 2 deprecation on the horizon and 2.7.5 being really, REALLY, **REALLY** out dated (Python 2.7.5 was released on May 15, 2013). This issue will not be fixed.

**Comment by joachimmetz** [comment]
Python 2 is end of life, closing issue
